pr: ['develop']
trigger: ['develop']

variables:
  azureSubscription: 'yw-brm-dev'
  pool: 'ase-release-pool'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'
  environmentDev: YW-RM-react-app-dev-env
  environmentProd: YW-RM-react-app-deploy-env
  rgDev: yw-brm-dev
  rgProd: yw-brm-dev
  webAppNameDev: 'ywBrmWebAppDev'
  webAppNameProd: 'ywBrmWebAppProd'


stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build  
        displayName: Build
        pool:
          name: $(pool)
        steps:
          - task: NodeTool@0
            displayName: ‘Use Node 10.x’
            inputs:
              versionSpec: 10.x
          - task: CmdLine@1
            displayName: ‘Run yarn’
            inputs:
              filename: yarn
              workingFolder: ‘$(Build.SourcesDirectory)’
          - task: Npm@1
            displayName: ‘npm run bundle’
            inputs:
              command: custom
              verbose: false
              customCommand: ‘run build’
          - task: CmdLine@1
            displayName: ‘Run Yarn for Develop’
            inputs:
              filename: yarn
              arguments: ‘--production --force’
              workingFolder: ‘$(Build.SourcesDirectory)’
          - task: ArchiveFiles@2
            displayName: ‘Archive $(System.DefaultWorkingDirectory)’
            inputs:
              rootFolderOrFile: ‘$(System.DefaultWorkingDirectory)’
              includeRootFolder: false
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              PathtoPublish: ‘$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip’
  - stage: Deploy_dev
    displayName: Deploy to dev
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentDev)
        pool:
          name: $(pool)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Azure Web App Deploy: {{ webAppNameDev }}'
                  inputs:
                    azureSubscription:  $(azureSubscription)
                    WebAppName: $(webAppNameDev)
                    deployToSlotOrASE: true
                    ResourceGroupName: $(rgDev)
                    packageForLinux: ‘$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip’
                    WebConfigParameters: ‘-Handler iisnode -NodeStartFile server.js -appType node’
                    enableCustomDeployment: true
                    AdditionalArguments: ‘-retryAttempts:6 -retryInterval:10000 -allowUntrusted’
