# Docker
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr: ['develop']
trigger: ['develop']

variables:
  imageRepository: 'YW-FE'
  dockerfilePath: 'Dockerfile'
  dockerRegistryServiceConnection: 'ywwwdevacr'
  subscriptionID: 'yw-ww-dev-kv-access'

steps:
- task: AzureKeyVault@1
  inputs:
    azureSubscription: $(subscriptionID)
    KeyVaultName: 'ywwwksdev'
    SecretsFilter: '*'
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    arguments: --build-arg client_secret=$(client-secret)
    repository: $(imageRepository)
    tags: latest
- task: Docker@2
  displayName: Push image
  inputs:
    command: push
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: latest
- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: $(dockerRegistryServiceConnection)



