pr: ['develop']
trigger: ['develop']

variables:
  azureSubscription: 'yw-brm-dev'
  pool: 'ase-release-pool'
  environmentDev: YW-RM-react-app-dev-env
  environmentProd: YW-RM-react-app-deploy-env
  rgDev: yw-brm-dev
  rgProd: yw-brm-dev
  webAppNameDev: 'ywBrmWebAppDev'
  webAppNameProd: 'ywBrmWebAppProd'


stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build  
        displayName: Build
        pool:
          name: $(pool)
        steps:
          - task: NodeTool@0
            displayName: ‘Use Node 10.x’
            inputs:
              versionSpec: 10.x
          - task: CmdLine@2
            inputs:
              script: 'yarn' 
          - task: CmdLine@2
            inputs:
              script: 'yarn run build'
          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop
  - stage: Deploy_dev
    displayName: Deploy to dev
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentDev)
        pool:
          name: $(pool)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Azure Web App Deploy'
                  inputs:
                    azureSubscription:  $(azureSubscription)
                    WebAppName: $(webAppNameDev)
                    deployToSlotOrASE: true
                    ResourceGroupName: $(rgDev)
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    WebConfigParameters: ‘-Handler iisnode -NodeStartFile server.js -appType node’
                    enableCustomDeployment: true
                    AdditionalArguments: ‘-retryAttempts:6 -retryInterval:10000 -allowUntrusted’
