# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  repoDir: 'yw-react-fe/yw-fe'
  uiSource: '$(reposDir)/src'
  uiBuild: "$(repoDir)/build"

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd $(uiSource)
    yarn install
    yarn run test
    yarn run build
  displayName: 'yarn install and build'

- task: CopyFiles@2
  inputs:
    Contents: '$(uiBuild)/**' # Pull the build directory (React)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'www' # output artifact named wwww
