# Docker
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pr: ['develop']
trigger: ['develop']


variables:
  azureSubscription: 'yw-brm-dev'
  pool: 'ase-release-pool'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'
  environmentName: 'ywBrmWebAppDev'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: $(pool)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'

          - script: |
              yarn install
              yarn run build
            displayName: 'yarn install, build and test'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy

    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          name: $(pool)
          displayName: Deploy
          environment: $(environmentName)

          strategy:
            runOnce:
              deploy:
                steps:
                  - task: AzureWebApp@1
                    displayName: 'Azure Web App Deploy: {{ webAppName }}'
                    inputs:
                      azureSubscription: $(azureSubscription)
                      appName: $(webAppName)
                      runtimeStack: 'NODE|10.10'
                      package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                      startUpCommand: 'npm run start'
