FROM node:14.4.0-alpine
RUN npm install -g yarn

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin:$PATH to $path`
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# add app
COPY . ./

RUN yarn run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

